version: '3.1'

services:

  db:
    image: postgis/postgis
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: ride-spark
    container_name: postgres
    volumes:
      - ./data:/var/lib/postgresql/data
